---
# setup_bashrc
- name: Get home directory of specific user
  ansible.builtin.shell: "eval echo ~{{ home_user }}"
  register: user_home
  changed_when: false

- name: Update .bashrc for specific user
  ansible.builtin.blockinfile:
    path: "{{ user_home.stdout }}/.bashrc"
    block: |
      # kubectl configurations
      source <(kubectl completion bash)
      alias k=kubectl
      complete -F __start_kubectl k

      # kubectl krew configurations
      if [ -d "${KREW_ROOT:-$HOME/.krew}/bin" ]; then
        export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
      fi
  become: false
  notify:
    - reload bashrc

# install kubectl
- name: Check if kubectl is installed
  ansible.builtin.stat:
    path: /usr/local/bin/kubectl
  register: kubectl_stat

- name: Set kubectl_installed fact
  ansible.builtin.set_fact:
    kubectl_installed: "{{ kubectl_stat.stat.exists }}"

- name: Add required tools (Debian/Ubuntu)
  ansible.builtin.apt:
    name:
      - gnupg
      - software-properties-common
      - wget
      - curl
      - git
    state: present
    update_cache: true
  when: ansible_os_family == 'Debian'
  become: true

- name: Retrieve the latest kubectl version
  ansible.builtin.command:
    cmd: "curl -L -s https://dl.k8s.io/release/stable.txt"
  register: latest_kubectl_version
  changed_when: false

- name: Install kubectl using binary
  block:
    - name: Download kubectl binary
      ansible.builtin.get_url:
        url: "https://dl.k8s.io/release/{{ latest_kubectl_version.stdout }}/bin/linux/amd64/kubectl"
        dest: "/tmp/kubectl"
        mode: '0755'
        force: false

    - name: Install kubectl
      ansible.builtin.copy:
        src: "/tmp/kubectl"
        dest: "/usr/local/bin/kubectl"
        owner: root
        group: root
        mode: '0755'
        remote_src: true
      become: true

    - name: Clean up the downloaded binary
      ansible.builtin.file:
        path: "/tmp/kubectl"
        state: absent
  when: not kubectl_installed

# install krew
- name: Check if krew is installed
  ansible.builtin.shell: kubectl krew version
  register: krew_check
  failed_when: false
  changed_when: false

- name: Ensure git is installed RHEL/CentOS
  ansible.builtin.yum:
    name: git
    state: present
  become: true
  when: ansible_os_family == 'RedHat'

- name: Install krew
  block:
    - name: Download and Install krew
      ansible.builtin.shell: |
        set -e
        if ! kubectl krew version; then
          cd "$(mktemp -d)"
          OS="$(uname | tr '[:upper:]' '[:lower:]')"
          ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')"
          KREW="krew-${OS}_${ARCH}"
          curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz"
          tar zxvf "${KREW}.tar.gz"
          ./"${KREW}" install krew
        fi
      args:
        executable: /bin/bash
      environment:
        KREW_ROOT: "{{ user_home.stdout }}/.krew"
        PATH: "{{ ansible_env.PATH }}:{{ user_home.stdout }}/.krew/bin"
      become: false
      register: krew_install_result
      changed_when: "'Added krew' in krew_install_result.stdout"
  when: krew_check.rc != 0

# install krew_plugins
- name: Check if krew plugin is already installed
  ansible.builtin.shell: "kubectl krew list | grep -w {{ item }}"
  loop: "{{ krew_plugins }}"
  register: installed_plugins
  changed_when: false
  failed_when: installed_plugins.rc > 1
  when: krew_plugins is defined
  environment:
    KREW_ROOT: "{{ user_home.stdout | default(ansible_env.HOME) }}/.krew"
    PATH: "{{ user_home.stdout | default(ansible_env.HOME) }}/.krew/bin:{{ ansible_env.PATH }}"

- name: Install krew plugins
  ansible.builtin.shell: "kubectl krew install {{ item }}"
  loop: "{{ krew_plugins }}"
  when:
    - krew_plugins is defined
    - item not in installed_plugins.results | map(attribute='stdout') | list
  args:
    executable: /bin/bash
  environment:
    KREW_ROOT: "{{ user_home.stdout | default(ansible_env.HOME) }}/.krew"
    PATH: "{{ user_home.stdout | default(ansible_env.HOME) }}/.krew/bin:/usr/local/bin:{{ ansible_env.PATH }}"
  become: false
  register: plugin_install_result
  changed_when: "'Added plugin' in plugin_install_result.stdout"
