---
- name: Converge
  hosts: all
  become: true
  vars:
    home_user: "somaz"
    krew_plugins:
      - "ctx"
      - "neat"
      - "ns"

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      when: ansible_os_family == 'Debian'

    - name: Update yum cache
      ansible.builtin.yum:
        update_cache: true
      when: ansible_os_family == 'RedHat'

  roles:
    - role: ansible_kubectl_krew

  post_tasks:
    - name: Set ownership for .krew directory
      ansible.builtin.file:
        path: "~{{ home_user }}/.krew"
        owner: "{{ home_user }}"
        group: "{{ home_user }}"
        recurse: true
        state: directory
