---
- name: Prepare
  hosts: all
  gather_facts: true
  tasks:
    - name: Fix PAM configuration for Docker containers (RedHat family)
      ansible.builtin.copy:
        dest: /etc/pam.d/system-auth
        content: |
          auth sufficient pam_permit.so
          account sufficient pam_permit.so
          password sufficient pam_permit.so
          session sufficient pam_permit.so
        owner: root
        group: root
        mode: '0644'
        backup: true
      when:
        - ansible_os_family == 'RedHat'
      become: true

    - name: Create test user
      ansible.builtin.user:
        name: "{{ home_user | default('somaz') }}"
        shell: /bin/bash
        create_home: true
        state: present
      become: true
