---
- name: Verify
  hosts: all
  vars:
    home_user: "somaz"
  tasks:
    - name: Check if kubectl is installed
      ansible.builtin.command: kubectl version --client
      register: kubectl_result
      failed_when: kubectl_result.rc != 0
      changed_when: false

    - name: Check if krew is installed
      ansible.builtin.command:
        cmd: "/home/{{ home_user }}/.krew/bin/kubectl-krew version"
      register: krew_result
      failed_when: krew_result.rc != 0
      changed_when: false
