---
- name: Verify
  hosts: all
  tasks:
    - name: Include vars
      include_vars: ../../vars/main.yml

    - name: Check if kubectl is installed
      command: kubectl version --client
      register: kubectl_result
      failed_when: kubectl_result.rc != 0
      changed_when: false

    - name: Check if krew is installed
      command: "/home/{{ home_user }}/.krew/bin/kubectl-krew version"
      register: krew_result
      failed_when: krew_result.rc != 0
      changed_when: false
